version: "3.9"
services:
  db: 
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: signalboard
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U user -d signalboard"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: